name : Practice-Exercise-workflow-2
on: 
    [push,workflow_dispatch]

jobs:
    AllInOne:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJs
              uses: actions/setup-node@v4
              with: 
               node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
            - name: Test Project
              run: npm test
            - name: Lint Run
              run: npm run lint
            - name: Deploy project
              run: echo "Deploying..."
   